---
- hosts: localhost

  vars:
    corebrightness_plist: /private/var/root/Library/Preferences/com.apple.CoreBrightness.plist
    safari_domain: ~/Library/Containers/com.apple.Safari/Data/Library/Preferences/com.apple.Safari

  tasks:
    - name: "Get userID"
      shell: "dscl . -read /Users/$(whoami)/ GeneratedUID | cut -d' ' -f2"
      register: userID

    - name: "Configure nightshift: warmest, scheduled sunset -> sunrise"
      shell: |
        /usr/libexec/PlistBuddy -c "Set :CBUser-{{ userID.stdout }}:CBBlueLightReductionCCTTargetRaw 2700" {{ corebrightness_plist }}
        /usr/libexec/PlistBuddy -c "Set :CBUser-{{ userID.stdout }}:CBBlueReductionStatus:BlueReductionEnabled 1" {{ corebrightness_plist }}
        /usr/libexec/PlistBuddy -c "Set :CBUser-{{ userID.stdout }}:CBBlueReductionStatus:BlueReductionMode 1" {{ corebrightness_plist }}
        killall cfprefsd
        killall corebrightnessd
      become: yes

    - name: "Show external drives on the desktop"
      osx_defaults:
        domain: com.apple.finder
        key: ShowExternalHardDrivesOnDesktop
        type: bool
        value: true

    - name: "Show removable media on the desktop"
      osx_defaults:
        domain: com.apple.finder
        key: ShowRemovableMediaOnDesktop
        type: bool
        value: true

    - name: "Disable extension rename warning"
      osx_defaults:
        domain: com.apple.finder
        key: FXEnableExtensionChangeWarning
        type: bool
        value: false

    - name: "Allow text selection in preview"
      osx_defaults:
        domain: com.apple.finder
        key: QLEnableTextSelection
        type: bool
        value: true

    - name: "Restart finder"
      command: killall Finder

    - name: "Don't automatically rearranged Spaces based on most recent use"
      osx_defaults:
        domain: com.apple.dock
        key: mru-spaces
        type: bool
        value: false

    - name: "Show ~/Library directory"
      command: chflags nohidden ~/Library

    - name: "Safari show favicons"
      osx_defaults:
        domain: "{{ safari_domain }}"
        key: ShowIconsInTabs
        type: bool
        value: true

    - name: "Safari show statusbar"
      osx_defaults:
        domain: "{{ safari_domain }}"
        key: ShowOverlayStatusBar
        type: bool
        value: true

    - name: "Safari show full URL"
      osx_defaults:
        domain: "{{ safari_domain }}"
        key: ShowFullURLInSmartSearchField
        type: bool
        value: true

    - name: "Safari disable autofill passwords"
      osx_defaults:
        domain: "{{ safari_domain }}"
        key: AutoFillPasswords
        type: bool
        value: false

    - name: "Safari show develop menu"
      osx_defaults:
        domain: "{{ safari_domain }}"
        key: IncludeDevelopMenu
        type: bool
        value: true

    - name: "Safari restore previous session"
      osx_defaults:
        domain: "{{ safari_domain }}"
        key: AlwaysRestoreSessionAtLaunch
        type: bool
        value: true

    - name: "Safari don't restore private windows"
      osx_defaults:
        domain: "{{ safari_domain }}"
        key: ExcludePrivateWindowWhenRestoringSessionAtLaunch
        type: bool
        value: true

    - name: "Safari don't auto open safe downloads"
      osx_defaults:
        domain: "{{ safari_domain }}"
        key: AutoOpenSafeDownloads
        type: bool
        value: false

    - name: "Safari don't automatically purge history"
      osx_defaults:
        domain: "{{ safari_domain }}"
        key: HistoryAgeInDaysLimit
        type: int
        value: 365000

    - name: "Safari disable push notiifcation prompts"
      osx_defaults:
        domain: "{{ safari_domain }}"
        key: CanPromptForPushNotifications
        type: bool
        value: false

    - name: "Save to local disk before iCloud"
      osx_defaults:
        domain: NSGlobalDomain
        key: NSDocumentSaveNewDocumentsToCloud
        type: bool
        value: false

    - name: "Check for software updates daily"
      osx_defaults:
        domain: com.apple.SoftwareUpdate
        key: ScheduleFrequency
        type: int
        value: 1

    - name: "Disable autocorrect"
      osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticSpellingCorrectionEnabled
        type: bool
        value: false

    - name: "Prompt for password immediately after screensaver/sleep"
      osx_defaults:
        domain: com.apple.screensaver
        key: askForPassword
        type: int
        value: 1

    - name: "Prompt for password immediately after screensaver/sleep"
      osx_defaults:
        domain: com.apple.screensaver
        key: askForPasswordDelay
        type: int
        value: 0

    - name: "Don't create .DS_Store on networked volumes"
      osx_defaults:
        domain: com.apple.desktopservices
        key: DSDontWriteNetworkStores
        type: bool
        value: true

    - name: "Remove all non default apps from dock"
      osx_defaults:
        domain: com.apple.dock
        key: static-only
        type: bool
        value: true

    - name: "Don't show recent apps in dock"
      osx_defaults:
        domain: com.apple.dock
        key: show-recents
        type: bool
        value: false

    - name: "Show hidden items in dock"
      osx_defaults:
        domain: com.apple.dock
        key: showhidden
        type: bool
        value: true

    - name: "Auto hide dock"
      osx_defaults:
        domain: com.apple.dock
        key: autohide
        type: bool
        value: true

    - name: "Resize dock icons"
      osx_defaults:
        domain: com.apple.dock
        key: tilesize
        type: float
        value: 36

    - name: "Restart dock"
      command: killall Dock

    - name: "Trackpad three finger drag"
      osx_defaults:
        domain: com.apple.AppleMultitouchTrackpad
        key: TrackpadThreeFingerDrag
        type: bool
        value: true

    - name: "Trackpad 2 finger notifications"
      osx_defaults:
        domain: com.apple.AppleMultitouchTrackpad
        key: TrackpadTwoFingerFromRightEdgeSwipeGesture
        type: int
        value: 3

    - name: "Hide siri menu bar"
      osx_defaults:
        domain: com.apple.Siri
        key: StatusMenuVisible
        type: int
        value: 0

    - name: "iTerm2 Margin"
      osx_defaults:
        domain: com.googlecode.iterm2
        key: TerminalMargin
        type: int
        value: 2

    - name: "Amethyst window margin"
      osx_defaults:
        domain: com.amethyst.Amethyst
        key: window-margin-size
        type: float
        value: 6

    - name: "Amethyst disable layout name"
      osx_defaults:
        domain: com.amethyst.Amethyst
        key: enables-layout-hud-on-space-change
        type: bool
        value: false

    - name: "Amethyst mouse swaps windows"
      osx_defaults:
        domain: com.amethyst.Amethyst
        key: mouse-swaps-windows
        type: bool
        value: true
