---
- hosts: localhost

  vars:
    dotfiles_loc: "{{ ansible_env.HOME }}/Projects/personal/dotfiles"

  tasks:
  - name: "dotfiles"
    block:

    - name: "Clone dotfiles"
      git:
        repo: git@github.com:sbaildon/dotfiles.git
        dest: "{{ dotfiles_loc }}"
        recursive: yes
        accept_hostkey: yes

    - name: "Stow dotfiles"
      command: "stow -t {{ ansible_env.HOME}}/ {{ item }}"
      args:
        chdir: "{{ dotfiles_loc }}"
      with_items:
        - git
        - fish
        - npm
        - nvim
        - rg
        - tmux
        - gnupg
        - base16-shell
        - vscode
        - iterm2
        - little-snitch
        - bat

    - name: "Install terminfo"
      command: "tic -x {{ item }}"
      args:
        chdir: "{{ dotfiles_loc }}"
      with_items:
        - terminfo/xterm-256color.terminfo
        - terminfo/tmux-256color.terminfo

    - name: "Install vim plugins"
      command: "nvim +PlugInstall +qa"
