---
- hosts: localhost
  tasks:

  - name: "fish shell"
    block:
    - name: "Find fish shell"
      shell: "type -p fish"
      register: fish

    - name: "Enable fish"
      lineinfile:
        path: /etc/shells
        line: "{{ fish.stdout }}"
        state: present
      become: yes

    - name: "Get username"
      become: false
      local_action: command whoami
      register: username
        
    - name: "Set fish shell"
      user:
        name: "{{ username.stdout }}"
        shell: "{{ fish.stdout }}"
      become: yes
