---
- hosts: localhost
  tasks:

    - name: "Install packages"
      homebrew:
        formula: "{{ item }}"
        state: present
      loop:
        - neovim
        - vim
        - curl
        - go
        - jq
        - yarn
        - node
        - httpie
        - git
        - fish
        - ripgrep
        - fd
        - tmux
        - tree
        - n
        - entr
        - kubernetes-cli
        - bat
        - fzf
        - python
        - make
        - stow
        - gpg
        - vault
        - wireguard-go
        - pyenv
        - dnsmasq
        - docker-machine-driver-hyperkit
        - protobuf
        - watch
        - telnet
        - dos2unix
        - libtool
        - brew-cask-completion
        - fortune
        - sl

    - name: "Install cask packages"
      homebrew_cask:
        name: "{{ item }}"
        state: present
      loop:
        - docker
        - amethyst
        - google-chrome
        - firefox
        - 1password
        - 1password-cli
        - bettertouchtool
        - fantastical
        - little-snitch
        - visual-studio-code
        - steam
        - discord
        - notion

    - name: "Install neovim python"
      pip:
        name: "neovim"
        executable: "pip3"
        extra_args: --user
