---
- hosts: localhost
  tasks:

    - name: "Install packages"
      homebrew:
        name: "{{ item }}"
        state: present
      with_items:
        - neovim
        - vim
        - curl
        - go
        - jq
        - yarn
        - node
        - httpie
        - git
        - fish
        - ripgrep
        - fd
        - tmux
        - tree
        - dep
        - n
        - entr
        - kubernetes-cli
        - bat
        - fzf
        - python
        - python@2
        - make
        - stow
